# Generated by Django 2.0.2 on 2018-02-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Iqar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_number', models.CharField(max_length=20, unique=True)),
                ('location', models.CharField(max_length=20)),
                ('area', models.IntegerField()),
                ('contents', models.CharField(max_length=20)),
                ('purpose', models.CharField(max_length=20)),
                ('date_owned', models.CharField(max_length=20)),
                ('currencies', models.CharField(max_length=20)),
                ('value_1', models.DecimalField(decimal_places=2, max_digits=20)),
                ('value_2', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
    ]
